apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: vickym19/app_backend:1  
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "54.179.254.204"  
        - name: DB_USER
          value: "postgres"  
        - name: DB_PASSWORD
          value: "vicky"  
        - name: DB_NAME
          value: "emp_test"  
        - name: DB_PORT
          value: "5432" 
        - name: ALLOWED_ORIGINS
          value: "http://localhost:3000"  

